
OPENAI_API_KEY = "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"


[connections.mysql_db]
dialect = "mysql"
driver = "mysqlconnector"
host = "localhost"
port = 3306
database = "dalba_seeding_db"
username = "Moon"
password = "1234"

